"""Timing constants for machine operations (seconds)."""

POSITION_180_TIME = 3
HYDRAULIC_MOVE_TIME = 16
MIXER_ROTATE_LONG = 60
MIXER_ROTATE_SHORT = 30
COOK_WAIT = 120
VALVE_OPEN_TIME = 10
VALVE_CLOSE_WAIT = 3
VALVE_DISPENSE_TIME = 20
SAFE_STOP_DELAY = 0.5

# Auto mode cycle times
AUTO_RICE_BOWL_TIME = 10
AUTO_MIXER_TIME = 10
AUTO_VALVE_OPEN_TIME = 5
AUTO_VALVE_CLOSE_WAIT = 3
